import { createContext, useContext, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { categories, initialPosts, products, reference, routeInfo, type Post } from './data';
import { Markdown } from './Markdown';

type User = { name: string; email: string };
const Auth = createContext<{ user: User | null; loading: boolean; refresh: () => Promise<void> }>({ user: null, loading: true, refresh: async () => {} });
async function api<T>(path: string, init?: RequestInit): Promise<T> {
 const res = await fetch('/api' + path, { credentials: 'same-origin', ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } });
 const data = await res.json() as T & { error?: string };
 if (!res.ok) throw new Error(data.error || 'Something went wrong. Please try again.');
 return data;
}
function AuthProvider({ children, enabled }: { children: ReactNode; enabled: boolean }) {
 const [user, setUser] = useState<User | null>(null), [loading, setLoading] = useState(enabled);
 const refresh = async () => { try { const data = await api<{ user: User | null }>('/auth/session'); setUser(data.user); } catch { setUser(null); } finally { setLoading(false); } };
 useEffect(() => { if (enabled) void refresh(); }, [enabled]);
 return <Auth.Provider value={{ user, loading, refresh }}>{children}</Auth.Provider>;
}
function Header({ path }: { path: string }) {
 const [open, setOpen] = useState(false);
 const links = [['/', 'Home'], ['/about', 'About us'], ['/solutions', 'Solutions'], ['/teams', 'Teams'], ['/blog', 'Insights']];
 return <header className="site-header"><div className="nav-wrap"><a href="/" aria-label="DJI Enterprise portfolio home" className="brand"><img src="/images/dji-enterprise.svg" width="210" height="36" alt="DJI Enterprise" /></a><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="main-navigation" onClick={() => setOpen(!open)}><span /><span /><span /></button><nav id="main-navigation" aria-label="Main navigation" className={open ? 'nav-links is-open' : 'nav-links'}>{links.map(([url, label]) => <a key={url} href={url} aria-current={path === url ? 'page' : undefined}>{label}</a>)}<a className="nav-cta" href="/solutions#platforms">Explore platforms</a></nav></div></header>;
}
function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><a href="/" className="brand footer-brand"><img src="/images/dji-enterprise.svg" width="210" height="36" loading="lazy" alt="DJI Enterprise" /></a><p>Aerial perspective.<br />Informed response.</p></div><div><h2>Explore</h2><a href="/about">About us</a><a href="/solutions">Solutions</a><a href="/teams">Teams</a></div><div><h2>Field insights</h2><a href="/blog">Read the journal</a><a href="/create-blog">Create an article</a><a href="/login">Editor login</a></div><div><h2>Official DJI resources</h2><a href={reference}>Wildfire solutions</a><a href="https://enterprise.dji.com/contact-us">Contact DJI</a><a href="https://www.dji.com/company">Company information</a></div></div><div className="container footer-note"><p>Independent educational portfolio by Wili K. Reference material and product imagery belong to DJI. This website is not operated by DJI.</p><span>Code Challenge 2 · 2026</span></div></footer>; }
function SectionHead({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="section-head"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{description && <p className="lead">{description}</p>}</div>; }
function PageHead({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="page-head container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{description}</p></div>; }
function PlatformCards({ detailed = false }: { detailed?: boolean }) { return <div className="grid gap-6 md:grid-cols-3">{products.map(p => <article className="platform-card" id={p.id} key={p.id}><div className="platform-image"><img src={p.image} alt={p.name + ' enterprise drone'} width="320" height="240" loading="lazy" /></div><div className="platform-content"><p className="eyebrow">{p.label}</p><h3>{p.name}</h3><p>{p.description}</p><dl className="spec-grid"><div><dt>Max. flight time*</dt><dd>{p.time}</dd></div><div><dt>Approx. weight</dt><dd>{p.weight}</dd></div></dl>{detailed && <ul className="feature-list">{p.features.map(f => <li key={f}>{f}</li>)}</ul>}<a className="text-link" href={detailed ? p.link : '/solutions#' + p.id}>{detailed ? 'Official product details' : 'Explore this platform'}</a></div></article>)}</div>; }
function Testimonial() { return <section className="testimonial-section"><div className="container testimonial-inner"><div><p className="eyebrow">From the field</p><h2>A better view for the people on the ground.</h2></div><div><blockquote>“Timely and accurate communication is essential in getting the right resources in place to mitigate an incident.”</blockquote><p className="quote-source">Chief Richard Fields · Los Angeles Fire Department</p><a className="text-link" href="https://enterprise-insights.dji.com/user-stories/lafd-deploys-drones-for-more-effective-air-operations">Read the DJI case study</a></div></div></section>; }
function Workflow() { return <div className="workflow-grid">{[['01', 'Observe', 'Survey the affected area using visual and thermal imagery.'], ['02', 'Locate', 'Record the position and context of potential hotspots.'], ['03', 'Coordinate', 'Share aerial observations with the incident command team.'], ['04', 'Review', 'Keep images and mapping results for post-incident analysis.']].map(([n, title, body]) => <div className="workflow-item" key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div>; }
function Home() { return <><section className="hero"><picture><source media="(max-width: 600px)" srcSet="/images/wildfire-480.webp" /><source media="(max-width: 1100px)" srcSet="/images/wildfire-900.webp" /><img src="/images/wildfire-1600.webp" width="1600" height="900" alt="Aerial view of smoke rising over a forest wildfire" fetchPriority="high" /></picture><div className="hero-shade" /><div className="hero-content"><p className="hero-eyebrow">DJI Enterprise · Public safety</p><h1>A clearer view.<br />A faster response.</h1><p>Aerial and thermal intelligence for the teams protecting our forests.</p><a className="button button-light" href="/solutions">Explore wildfire solutions</a></div><div className="hero-caption">Wildfire reconnaissance · Thermal imaging · Mission coordination</div></section><section className="section container"><SectionHead eyebrow="Wildfire response" title="See more. Decide with confidence." description="Changing conditions demand a shared picture of the incident. Aerial tools help teams look beyond the ground-level view." /><div className="benefit-grid">{[['Understand the incident', 'Visual and thermal views help operators assess an affected area and identify potential hotspots.'], ['Support ground teams', 'Location information gives incident commanders another input when coordinating response.'], ['Build a useful record', 'Mission imagery and mapping help teams document observations and review the response.']].map(([t, d], i) => <article className="benefit-card" key={t}><span className="benefit-number">0{i + 1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="section section-muted" id="platforms"><div className="container"><SectionHead eyebrow="Purpose-built platforms" title="The right tools for the mission." description="Three different approaches to aerial reconnaissance, selected from DJI’s wildfire solution reference." /><PlatformCards /><p className="small-note">*Manufacturer maximum flight times under stated test conditions. Actual endurance varies with payload, weather, and mission planning.</p></div></section><section className="section container"><SectionHead eyebrow="A connected workflow" title="From the first flight to the final review." /><Workflow /></section><Testimonial /><section className="section container"><div className="section-title-row"><SectionHead eyebrow="Field insights" title="Knowledge worth sharing." /><a className="text-link" href="/blog">Read all insights</a></div><div className="grid gap-6 md:grid-cols-3">{initialPosts.map(p => <PostCard post={p} key={p.id} />)}</div></section></>; }
function About() { return <><PageHead eyebrow="About DJI" title="Engineering a new perspective." description="DJI brings together flight systems, imaging, and software to help people work with the world from above." /><section className="container about-split"><img src="/images/field.webp" alt="DJI aerial technology used in a wildfire response setting" width="1000" height="640" /><div><p className="eyebrow">The company story</p><h2>From flight technology to tools for work.</h2><p>Founded in 2006 and headquartered in Shenzhen, DJI develops aerial platforms and imaging technology for creative and professional applications.</p><p>DJI Enterprise applies that engineering to practical tasks including mapping, inspection, and public safety. In wildfire response, the focus is on giving trained teams useful visual, thermal, and location information.</p><a className="text-link" href="https://www.dji.com/company">Explore DJI’s official company profile</a></div></section><section className="section section-muted"><div className="container"><SectionHead eyebrow="Culture and collaboration" title="Good engineering connects people." description="Creativity, shared learning, and practical problem-solving guide the workflow presented in this portfolio." /><div className="benefit-grid"><article className="benefit-card"><h3>Flight and imaging</h3><p>Hardware engineers connect aircraft, sensors, control systems, and dependable field operation.</p></article><article className="benefit-card"><h3>Software and data</h3><p>Software teams turn collected imagery and locations into information people can use.</p></article><article className="benefit-card"><h3>Operations and learning</h3><p>Pilots and response teams bring operational context, feedback, and training into the workflow.</p></article></div></div></section><section className="section container"><SectionHead eyebrow="Demonstration team" title="People behind a connected workflow." description="Names, roles, and short bios illustrate how complementary disciplines work together." /><TeamProfiles limit={3} heading="h3" /><a className="button button-dark mt-8" href="/teams">Meet the full demonstration team</a></section></>; }
function Solutions() { return <><PageHead eyebrow="Products and services" title="Build around the mission." description="Choose an aerial platform, then connect the imaging and software tools your operational task needs." /><section className="container section section-topless" id="platforms"><h2 className="sr-only">Available wildfire platforms</h2><PlatformCards detailed /><p className="small-note">Specifications are summarized from DJI’s official wildfire reference. Pricing depends on the equipment package and region; consult an authorized DJI dealer. Flight times are manufacturer maxima under test conditions.</p></section><section className="section section-muted"><div className="container"><SectionHead eyebrow="Supporting software" title="Turn aerial views into shared context." /><div className="benefit-grid">{[['DJI Pilot 2', 'Ground control and mission execution.', 'https://enterprise.dji.com'], ['DJI Terra', 'Mapping, modeling, and flight mission planning.', 'https://enterprise.dji.com/dji-terra'], ['DJI FlightHub 2', 'Cloud management for drones and docks.', 'https://enterprise.dji.com/flighthub-2']].map(([t, d, url]) => <article className="software-card" key={t}><span className="software-mark" aria-hidden="true">{t.replace('DJI ', '').split(' ')[0].slice(0, 1)}</span><h3>{t}</h3><p>{d}</p><a className="text-link" href={url}>Official software information</a></article>)}</div></div></section><section className="section container"><SectionHead eyebrow="Mission workflow" title="Observe. Locate. Coordinate. Review." /><Workflow /></section><Testimonial /><section className="container contact-strip"><div><h2>Explore an equipment package.</h2><p>Contact DJI for product information, demonstrations, and dealer availability.</p></div><a className="button button-dark" href="https://enterprise.dji.com/contact-us">Contact DJI</a></section></>; }
type Person = { name: { first: string; last: string }; picture: { large: string } };
const roles = ['Flight systems engineer', 'Thermal imaging specialist', 'Mission software engineer', 'Field operations lead', 'Geospatial analyst', 'Training coordinator'];
const bios = ['Connects aircraft design with the practical demands of field operations.', 'Helps teams interpret complementary visual and infrared observations.', 'Builds clear workflows for mission information and coordination.', 'Brings pilot feedback and operational context into planning.', 'Turns aerial observations into useful geographic context.', 'Supports consistent preparation, documentation, and team learning.'];
function TeamProfiles({ limit = 6, heading: Heading = 'h2' }: { limit?: number; heading?: 'h2' | 'h3' }) {
 const [people, setPeople] = useState<Person[]>([]);
 const [error, setError] = useState('');
 const [loading, setLoading] = useState(true);
 const load = async () => {
  setLoading(true);
  setError('');
  try {
   const response = await fetch('https://randomuser.me/api/?results=6&seed=dji-wildfire-2026&nat=gb,us,au&inc=name,picture&noinfo', { signal: AbortSignal.timeout(12000) });
   if (!response.ok) throw new Error('The profile service is temporarily unavailable. Please try again.');
   const data = await response.json() as { results: Person[] };
   if (!Array.isArray(data.results) || data.results.length !== 6) throw new Error('The profile service returned incomplete profiles.');
   setPeople(data.results.slice(0, limit));
  } catch (e) { setError((e as Error).message); }
  finally { setLoading(false); }
 };
 useEffect(() => { void load(); }, [limit]);
 return <>
  <div className="notice">These sample profiles are fetched from Random User. They illustrate this portfolio’s team features and do not represent DJI employees.</div>
  {error && <div className="error-panel" role="alert"><p>{error}</p><button className="button button-dark" onClick={load}>Try loading profiles again</button></div>}
  <div className="team-grid" aria-busy={loading}>
   {loading ? roles.slice(0, limit).map(role => <article className="team-card skeleton" key={role}><div className="avatar-placeholder" /><div className="skeleton-line" /><p>{role}</p></article>) : people.map((person, i) => <article className="team-card" key={person.name.first + person.name.last}>
    <img src={person.picture.large} alt={person.name.first + ' ' + person.name.last} width="128" height="128" loading="lazy" />
    <Heading>{person.name.first} {person.name.last}</Heading><p className="team-role">{roles[i]}</p><p>{bios[i]}</p>
   </article>)}
  </div>
 </>;
}
function Teams() {
 return <><PageHead eyebrow="People and disciplines" title="A mission is a team effort." description="A demonstration of the engineering and operational roles that connect an aerial workflow." /><section className="container section section-topless"><TeamProfiles /></section></>;
}
function date(iso: string) { return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }); }
function PostCard({ post }: { post: Post }) { return <article className="post-card"><a href={'/blog/' + post.id} tabIndex={-1} aria-hidden="true"><img src={post.image || '/images/wildfire-900.webp'} width="640" height="400" alt="" loading="lazy" /></a><div className="post-content"><p className="eyebrow">{post.category}</p><h3><a href={'/blog/' + post.id}>{post.title}</a></h3><p>{post.excerpt}</p><div className="post-meta"><span>{post.author}</span><time dateTime={post.publishedAt}>{date(post.publishedAt)}</time></div></div></article>; }
function Blog() { const [posts, setPosts] = useState(initialPosts), [category, setCategory] = useState('All'), [error, setError] = useState('');
 useEffect(() => { api<{ posts: Post[] }>('/posts').then(data => setPosts(data.posts)).catch(e => setError(e.message)); }, []);
 const visible = category === 'All' ? posts : posts.filter(p => p.category === category);
 return <><PageHead eyebrow="The field journal" title="Insight for the next mission." description="Original notes on thermal imaging, equipment selection, and the connected aerial workflow." /><section className="container section section-topless"><h2 className="sr-only">Journal articles</h2><div className="blog-toolbar"><div className="filter-group" aria-label="Filter articles by category">{['All', ...categories].map(c => <button key={c} aria-pressed={category === c} onClick={() => setCategory(c)} className={category === c ? 'filter active' : 'filter'}>{c}</button>)}</div><a className="text-link" href="/create-blog">Write an article</a></div>{error && <p className="notice" role="status">Live articles are temporarily unavailable. Showing the original journal entries. {error}</p>}<p className="sr-only" aria-live="polite">{visible.length} articles shown</p><div className="grid gap-6 md:grid-cols-3">{visible.map(p => <PostCard post={p} key={p.id} />)}</div>{!visible.length && <p className="empty-state">There are no articles in this category yet.</p>}</section></>; }
function Article({ id }: { id: string }) { const [post, setPost] = useState<Post | undefined>(initialPosts.find(p => p.id === id)), [error, setError] = useState('');
 useEffect(() => { api<{ post: Post }>('/posts/' + encodeURIComponent(id)).then(d => setPost(d.post)).catch(e => setError(e.message)); }, [id]);
 useEffect(() => { if (post) { document.title = post.title + ' | DJI Enterprise Portfolio'; document.querySelector('meta[name="description"]')?.setAttribute('content', post.excerpt); } }, [post]);
 return <section className="container article-wrap"><a className="text-link" href="/blog">All field insights</a>{post ? <article><p className="eyebrow mt-8">{post.category}</p><h1>{post.title}</h1><div className="post-meta"><span>{post.author}</span><time dateTime={post.publishedAt}>{date(post.publishedAt)}</time></div><img className="article-image" src={post.image || '/images/wildfire-900.webp'} alt="Wildfire response reference imagery" width="900" height="520" /><Markdown text={post.content} /><div className="tags">{post.tags.map(t => <span key={t}>{t}</span>)}</div></article> : <p role="status">{error || 'Loading article…'}</p>}</section>; }
function returnPath() { if (typeof window === 'undefined') return '/create-blog'; const path = new URLSearchParams(window.location.search).get('returnTo'); return path?.startsWith('/') && !path.startsWith('//') && !path.includes('\\') ? path : '/create-blog'; }
function Login() { const { user, loading, refresh } = useContext(Auth); const [error, setError] = useState(''), [busy, setBusy] = useState(false);
 useEffect(() => { if (user) window.location.replace(returnPath()); }, [user]);
 const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); setError(''); const data = new FormData(e.currentTarget); try { await api('/auth/login', { method: 'POST', body: JSON.stringify({ email: data.get('email'), password: data.get('password') }) }); await refresh(); window.location.assign(returnPath()); } catch (e) { setError((e as Error).message); setBusy(false); } };
 return <section className="auth-wrap container"><div className="auth-intro"><p className="eyebrow">Editorial access</p><h1>Share what you learn.</h1><p className="lead">Sign in to publish an original article to the field journal.</p><a className="text-link" href="/blog">Browse published insights</a></div><form className="form-card" onSubmit={submit}><h2>Editor login</h2><p>Use your assigned editor credentials.</p><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="username" required maxLength={254} /><label htmlFor="password">Password</label><input id="password" name="password" type="password" autoComplete="current-password" required maxLength={128} />{error && <p role="alert" className="form-error">{error}</p>}<button className="button button-dark" disabled={busy || loading}>{busy ? 'Signing in…' : loading ? 'Checking session…' : 'Sign in'}</button><p className="small-note">Publishing access is separate from DJI’s own accounts.</p></form></section>; }
function CreateBlog() { const { user, loading } = useContext(Auth); const [draft, setDraft] = useState({ title: '', content: '', category: categories[0], tags: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false), [preview, setPreview] = useState(false), [draftReady, setDraftReady] = useState(false);
 useEffect(() => { if (!loading && !user) window.location.replace('/login?returnTo=%2Fcreate-blog'); }, [loading, user]);
 useEffect(() => { try { const saved = sessionStorage.getItem('wildfire-editor-draft'); if (saved) { const d = JSON.parse(saved); if (typeof d.title === 'string' && typeof d.content === 'string') setDraft({ title: d.title, content: d.content, category: categories.includes(d.category) ? d.category : categories[0], tags: typeof d.tags === 'string' ? d.tags : '' }); } } catch {} setDraftReady(true); }, []);
 useEffect(() => { if (draftReady) try { sessionStorage.setItem('wildfire-editor-draft', JSON.stringify(draft)); } catch {} }, [draft, draftReady]);
 const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); setError(''); try { const data = await api<{ post: Post }>('/posts', { method: 'POST', body: JSON.stringify({ ...draft, tags: draft.tags.split(',').map(t => t.trim()).filter(Boolean) }) }); sessionStorage.removeItem('wildfire-editor-draft'); window.location.assign('/blog/' + data.post.id); } catch (e) { setError((e as Error).message); setBusy(false); } };
 return <section className="container editor-wrap"><PageHead eyebrow="Field journal" title="Create an article." description="Write a useful insight, choose a category, and publish it to the journal." />{loading || !user ? <p role="status" className="empty-state">Checking editorial access…</p> : <><div className="editor-account"><span>Signed in as {user.name}</span><button className="text-link" onClick={async () => { await api('/auth/logout', { method: 'POST' }); window.location.assign('/login'); }}>Sign out</button></div><form className="editor-form" onSubmit={submit}><label htmlFor="title">Article title</label><input id="title" value={draft.title} maxLength={120} required minLength={5} onChange={e => setDraft({ ...draft, title: e.target.value })} /><div className="grid gap-6 md:grid-cols-2"><div><label htmlFor="category">Category</label><select id="category" value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{categories.map(c => <option key={c}>{c}</option>)}</select></div><div><label htmlFor="tags">Tags <span className="optional">(comma-separated)</span></label><input id="tags" value={draft.tags} maxLength={200} onChange={e => setDraft({ ...draft, tags: e.target.value })} placeholder="thermal imaging, field operations" /></div></div><div className="editor-tabs"><span id="content-label">Article content</span><button type="button" aria-pressed={preview} className="text-link" onClick={() => setPreview(!preview)}>{preview ? 'Return to writing' : 'Preview Markdown'}</button></div>{preview ? <div className="markdown-preview"><Markdown text={draft.content || 'Your article preview will appear here.'} /></div> : <textarea aria-labelledby="content-label" aria-describedby="markdown-help" value={draft.content} required minLength={40} maxLength={20000} rows={15} onChange={e => setDraft({ ...draft, content: e.target.value })} />}<p id="markdown-help" className="small-note">Markdown supports headings, paragraphs, lists, bold text, links, and code blocks. Your draft is kept in this browser tab.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="publish-row"><a className="text-link" href="/blog">Back to the journal</a><button className="button button-dark" disabled={busy || draft.title.trim().length < 5 || draft.content.trim().length < 40}>{busy ? 'Publishing…' : 'Publish article'}</button></div></form></>}</section>; }
function NotFound() { return <div className="container empty-state"><h1>Page not found.</h1><p>Use the navigation to explore the wildfire portfolio.</p><a className="button button-dark" href="/">Return home</a></div>; }
export function App({ path }: { path: string }) { const meta = routeInfo[path]; useEffect(() => { if (meta) { document.title = meta.title; document.querySelector('meta[name="description"]')?.setAttribute('content', meta.description); } }, [path]); let page: ReactNode;
 switch (path) { case '/': page = <Home />; break; case '/about': page = <About />; break; case '/solutions': page = <Solutions />; break; case '/teams': page = <Teams />; break; case '/blog': page = <Blog />; break; case '/login': page = <Login />; break; case '/create-blog': page = <CreateBlog />; break; default: page = path.startsWith('/blog/') ? <Article id={decodeURIComponent(path.slice(6))} /> : <NotFound />; }
 return <AuthProvider enabled={path === '/login' || path === '/create-blog'}><a className="skip-link" href="#main-content">Skip to content</a><Header path={path} /><main id="main-content" tabIndex={-1}>{page}</main><Footer /></AuthProvider>;
}
