export const reference = 'https://enterprise.dji.com/public-safety/wildfires';
export const products = [
  { id: 'matrice-4t', name: 'DJI Matrice 4T', label: 'Portable response', image: '/images/matrice-4t.webp', description: 'A compact aerial platform for a first look at changing conditions. Visual and thermal cameras support initial risk assessment.', time: '49 min', weight: '1.2 kg', thermal: '640 × 512', link: 'https://enterprise.dji.com/matrice-4-series', features: ['Visual and thermal reconnaissance', 'Laser rangefinding', 'Rapid field deployment'] },
  { id: 'matrice-400', name: 'DJI Matrice 400', label: 'High-performance operations', image: '/images/matrice-400.webp', description: 'A larger platform for demanding missions. Pair with the Zenmuse H30T for thermal reconnaissance and night operations.', time: '59 min', weight: '9.7 kg', thermal: 'H30T payload', link: 'https://enterprise.dji.com/matrice-400', features: ['Interchangeable payloads', 'Extended mission endurance', 'Thermal and visual intelligence'] },
  { id: 'matrice-30t', name: 'DJI Matrice 30T', label: 'Versatile thermal reconnaissance', image: '/images/matrice-30t.webp', description: 'A balanced, weather-resistant platform combining visual, thermal, and rangefinding tools for incident assessment.', time: '41 min', weight: '3.8 kg', thermal: '640 × 512', link: 'https://enterprise.dji.com/matrice-30', features: ['Integrated thermal camera', 'Optical zoom', 'Hot-swappable batteries'] },
];
export interface Post { id: string; title: string; excerpt: string; content: string; category: string; tags: string[]; author: string; publishedAt: string; image: string }
export const categories = ['Field operations', 'Technology', 'Mission planning'];
export const initialPosts: Post[] = [
  { id: 'thermal-imaging-in-wildfire-response', title: 'What thermal imaging adds to wildfire response', excerpt: 'How visual and infrared views give incident teams complementary information about the same landscape.', category: 'Technology', tags: ['thermal imaging', 'wildfires'], author: 'Portfolio editorial team', publishedAt: '2026-09-30T08:00:00Z', image: '/images/wildfire-900.webp', content: '# Two views of the same incident\n\nA visual camera records the scene as people normally see it. A thermal camera records differences in infrared radiation. Used together, these views help a trained operator locate areas that need closer attention.\n\n## From image to decision\n\nDuring a wildfire mission, the operator can switch between visual and thermal views, inspect potential hotspots, and share their locations with the incident team. The usefulness of a temperature reading depends on equipment settings and environmental conditions.\n\n- Select the appropriate thermal palette and gain mode.\n- Compare a thermal observation with the visual scene.\n- Share a location and context with the ground team.\n- Record observations for the post-incident review.\n\n## People remain part of the workflow\n\nThermal imagery is one input to a response decision. Mission planning, airspace coordination, equipment selection, and an experienced incident commander remain essential.\n\nThis original portfolio article summarizes the workflow on [DJI’s wildfire solutions page](https://enterprise.dji.com/public-safety/wildfires).' },
  { id: 'choosing-a-wildfire-drone-platform', title: 'Choosing a platform around the mission', excerpt: 'Portability, payloads, and endurance are different tradeoffs. Start with the operational task.', category: 'Mission planning', tags: ['equipment', 'planning'], author: 'Portfolio editorial team', publishedAt: '2026-09-29T08:00:00Z', image: '/images/field.webp', content: '# Begin with the mission\n\nChoosing an aerial platform is a practical tradeoff between portability, endurance, and the sensors the task requires. A first-response vehicle and an established incident command team may need different equipment.\n\n## Portable reconnaissance\n\nThe Matrice 4T combines visual and thermal cameras in a compact platform. DJI presents it as an option for rapid deployment and initial assessment.\n\n## Payload flexibility\n\nThe Matrice 400 supports different payloads. DJI pairs it with the Zenmuse H30T in its high-performance wildfire response solution.\n\n## A balanced field platform\n\nThe Matrice 30T combines visual, thermal, and laser rangefinding capabilities. It is another option when an integrated field platform fits the mission.\n\nPublished maximum flight times describe manufacturer test conditions. Teams must plan around their actual payload, weather, battery reserve, and operational constraints. See the [official solution reference](https://enterprise.dji.com/public-safety/wildfires) for specifications.' },
  { id: 'from-reconnaissance-to-incident-review', title: 'From reconnaissance to incident review', excerpt: 'A useful mission delivers more than an image: it gives teams shared context and a record they can review.', category: 'Field operations', tags: ['workflow', 'documentation'], author: 'Portfolio editorial team', publishedAt: '2026-09-28T08:00:00Z', image: '/images/wildfire-900.webp', content: '# A shared picture of the incident\n\nAn aerial mission can help teams understand a changing fire area. Its value depends on how observations reach the people making decisions.\n\n## Observe\n\nA pilot surveys the affected area and examines visual and thermal imagery. The mission remains coordinated with the wider incident response.\n\n## Locate and communicate\n\nAn operator can record hotspot coordinates and share them with ground teams. Mission-management software helps organize imagery and location information.\n\n## Document\n\nImages and mapping results can support post-incident analysis and recovery planning. A consistent record helps teams explain what was observed and when.\n\nThe [DJI wildfire reference](https://enterprise.dji.com/public-safety/wildfires) describes reconnaissance, information sharing, and post-mission documentation as connected stages.' },
];
export const routeInfo: Record<string, { title: string; description: string }> = {
 '/': { title: 'Wildfire Solutions | DJI Enterprise Portfolio', description: 'Aerial and thermal imaging solutions for wildfire response. Explore platforms, mission workflows and field insights in this DJI portfolio adaptation.' },
 '/about': { title: 'About DJI | DJI Enterprise Portfolio', description: 'Explore DJI’s engineering story, aerial technology and the disciplines behind enterprise drone operations.' },
 '/solutions': { title: 'Drones and Solutions | DJI Enterprise Portfolio', description: 'Compare Matrice 4T, Matrice 400 and Matrice 30T aerial platforms and supporting software for wildfire reconnaissance.' },
 '/teams': { title: 'Teams | DJI Enterprise Portfolio', description: 'Meet the demonstration engineering and operations team. Profiles are fetched dynamically from the Random User API.' },
 '/blog': { title: 'Field Insights | DJI Enterprise Portfolio', description: 'Read original articles about thermal imaging, mission planning and wildfire drone operations.' },
 '/create-blog': { title: 'Create an Article | DJI Enterprise Portfolio', description: 'Sign in to write and publish a Markdown article to the portfolio’s field insights journal.' },
 '/login': { title: 'Editor Login | DJI Enterprise Portfolio', description: 'Secure editor sign-in for publishing original articles to the wildfire field insights journal.' },
};
